import { Inter } from "next/font/google";
import { Navbar } from "./components/navbar";
import "./globals.css";

const inter = Inter({
  subsets: ["latin"],
});


export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex min-h-screen">
          <Navbar 
          />
          <main className="flex-1 lg:ml-64 pt-16 lg:pt-0">
            {children}
          </main>
        </div>
      </body>
    </html>
  )
}
